package com.bhoomi.awsemployee.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
/**
 * JPA for  table
 * 
 * @filename Repository.java
 *
 * @author Chaitanya Bhoomireddy
 * 
 */
@DynamoDBTable(tableName = "employee")
public class Employee {
    private String id;
    private String name;
    private String department;
 
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
 
    @DynamoDBAttribute
    public String getName() {
        return name;
    }
 
    @DynamoDBAttribute
    public String getDepartment() {
        return department;
    }

	public void setId(String id) {
		this.id = id;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setDepartment(String department) {
		this.department = department;
	}
 
   
}